logging:
  level:
    org.hibernate.SQL: DEBUG

---

spring:
  profiles: postgresql
  jpa:
    generate-ddl: true
  datasource:
      initialize: false
      url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:db}
      username: ${DB_USER:db_user}
      password: ${DB_PASSWORD:db_password}
